### ISSUE TITLE
Initial development

### ISSUE THREAD

**Issue by ryan-jan** [ryan-jan/barry#1]
## Tasks

- [x] Fork the relevant code from the Terraform repo at version 1.5.7.
- [x] Implement attribute/block ordering/alphabetisation following the recommendations from the Terraform style guide:
    - When both arguments and blocks appear together inside a block body, place all of the arguments together at the top and then place nested blocks below them. Use one blank line to separate the arguments from the blocks.
    - For blocks that contain both arguments and "meta-arguments" (as defined by the Terraform language semantics), list meta-arguments first and separate them from other arguments with one blank line. Place meta-argument blocks last and separate them from other blocks with one blank line.
    - Top-level blocks should always be separated from one another by one blank line. Nested blocks should also be separated by blank lines, except when grouping together related blocks of the same type (like multiple provisioner blocks in a resource).
- [x] Change comments from `//` to `#`.
- [x] Fix "dangling" comments which would be erased as they are not directly attached to an attribute or block.
- [x] For `module` blocks ensure the very first two attributes are `source` and `version` if specified.
- [ ] Wrap multiline attributes with blank lines.
- [x] Format multiline attributes across multiple lines, do not alphabetise the keys of maps or change list order.
- [x] Change `:` to `=` in maps.
- [x] Set initial version to v0.1.0 as it is likely to be unstable for a while.
- [x] Fix directory processing.
- [x] Tidy logic in `formatBody` for readability and performance.
- [ ] Write documentation & README....boring!
